### ISSUE TITLE
运行不起来？

### ISSUE THREAD

**Issue by gatspy** [Thunf/grace-vue-webpack-boilerplate#3]
直接拷贝到koa-grace app目录下，cd到app下的grace-project ，安装依赖以后
运行npm run dev，提示错误 `Fail to match koa-grace server folder, normalize folder structure and retry`
目录结构就是clone下去的啊。。。请指教

----
上面问题搞定了。要依照koa-grace目录结构

```shell
.
├── app
│   └──grace-project
│         ├── build
│         ├── controller
│         ├── mock
│         ├── static
│         ├── views
│         └── vues
└── server
    ├── app
    │    └── grace-project
    ├── middleware
    ├── ...
```
vhost 怎么配置呢？ `已解决`

----
`模板`builld的 `dest`是 上面结构中server/app，上面的目录结构中，在前端项目中构建后，直接在server/app下生成了grace-project项目的目录结构。直接在vhost里配置就可以。
`dev.local.me`在hosts里映射成`127.0.0.1`

```js
module.exports = {
    vhost: {
        'dev.local.me': 'grace-project'
    }
}
```

**Comment by Thunf** [comment]
检测server文件夹结构这步，是通过查找server/config/main.development.js这个文件来实现的，可以检查一下这个路径是否OK。
如果还不OK，可以到build/check-server.js中断点findServerFolder/matchServerJson方法console.log(confMatch)的值，调试一下。
欢迎到grace群中提问题，issue有时候看的不及时不好意思
