### ISSUE TITLE
Bug: opn( path.join(uri, config.dev.autoOpenPage || '') )

### ISSUE THREAD

**Issue by jiaxingzheng** [Thunf/grace-vue-webpack-boilerplate#4]
build目录下open-browser.js文件中第88行代码opn( path.join(uri, config.dev.autoOpenPage || '') )中

path.join 会将参数以系统路径分隔符(windows下为\，linux下为/)进行拼接，并且双斜杠会被替换为单斜杠，
导致调用opn报错

解决方法：将该句代码替换为opn( uri + '/' + config.dev.autoOpenPage || '' )

**Comment by Thunf** [comment]
开windows试了一下，并没有复现，需要更多信息。
请详细描述复现过程 & 贴出来报错信息，方便查找问题。

**Comment by jiaxingzheng** [comment]
复现：
Windows [版本 10.0.15063]
![tim 20170807084743](https://user-images.githubusercontent.com/5601300/29008678-b07608c4-7b4d-11e7-8be8-584ae8743a21.png)
执行npm run dev：
![tim 20170807084819](https://user-images.githubusercontent.com/5601300/29008688-c50958f4-7b4d-11e7-9925-07da53eac261.png)
点击确定后，输出错误信息：
![tim 20170807084916](https://user-images.githubusercontent.com/5601300/29008693-db5e7120-7b4d-11e7-9c52-4eb214ea99da.png)

**Comment by Thunf** [comment]
node版本和npm版本是多少呢？

**Comment by jiaxingzheng** [comment]
![image](https://user-images.githubusercontent.com/5601300/29054927-e755448e-7c2b-11e7-885d-13326b4b7ab0.png)
