### ISSUE TITLE
无法使用百度统计或者腾讯统计

### ISSUE THREAD

**Issue by ChanJuanMei** [Thunf/grace-vue-webpack-boilerplate#7]
在app\wechat\views\_common\hook\baidu.html中添加统计的js， 在app\wechat\views\_common\layout.html中引入。代码如下： {% include "hook/baidu.html" %}  
可以无论如何都无法在统计后台看到数据，作者大大能帮忙看一下么

**Comment by ChanJuanMei** [comment]
最后我把统计的代码放在 /vues/demo/index.vue这种位置居然成功了，作者大大能改进一下么，放在这里不太优雅

**Comment by Thunf** [comment]
app\wechat\views_common\hook\baidu.html 里的代码检查一下，是不是**没包<script>**，示例文件里是这样的：

```
<script>
var _hmt = _hmt || [];
(function() {
    var hm = document.createElement("script");
    hm.src = "//hm.baidu.com/hm.js?1234567890";
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(hm, s);
})();
</script>
```

**Comment by ChanJuanMei** [comment]
包了的

**Comment by ChanJuanMei** [comment]
<script type="text/javascript">
      var _mtac = {"autoReport":0};
      (function() {
        var mta = document.createElement("script");
        mta.src = "http://pingjs.qq.com/xx.js?v2.0.4";
        mta.setAttribute("xx", "xx");
        mta.setAttribute("xx", "xx");
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(mta, s);
      })();
      </script>

**Comment by Thunf** [comment]
看一下页面响应里（控制台 -> Network -> Doc - Response），有没有这段？
我跑了一下最新的服务和模板，没有问题呀...

**Comment by ChanJuanMei** [comment]
有这段的。js也是可以请求到的

**Comment by ChanJuanMei** [comment]
不过我不是最新的

**Comment by ChanJuanMei** [comment]
代码里面我也没看到你引用过baidu.html这个文件呀

**Comment by Thunf** [comment]
模板里引用顺序是： 
- layout.html 里 {% include "foothook.html" %}
- foothook.html 里 {% include 'hook/baidu.html' %}

为了方便管理多种第三方脚本的，你跑一下模板看看能不能发出去？ 
按你说的，有这段，JS也可以请求到（说明hook这段运行了），那可能就是加载的脚本发送的问题了...

**Comment by ChanJuanMei** [comment]
你说的这些我都试过了，无论这段js放在view下的哪个html都不行，但是放在vues下面的模块的index.vue就可以。我已经测试很多遍了

**Comment by Thunf** [comment]
app\wechat\views_common\layout.html  中的 **views_common** 是你自己建的么？
server运行时，默认访问的是 views 目录下，确认一下：
- 若在views目录下有文件通过相对地址引用views_common下的内容 ，views_common需要在 build/webpack.base.conf.js 里的 CopyWebpackPlugin 里配置拷贝到server中
- 若不是以上情况，那么你需要更改的应该是 views 下的文件才对，server运行时，默认访问的是 views 目录

**Comment by ChanJuanMei** [comment]
这里不能截图，我的目录是views\ _common\baidu.html，而layout是views\layout.html

**Comment by ChanJuanMei** [comment]
layout.html引用的baidu.com在谷歌浏览器中可以看到代码运行了呢

**Comment by Thunf** [comment]
那就是加载统计脚本的代码运行了，然后腾讯的JS也加载进来了，但是在后台看不到数据对吧。。。
所以你看的数据是PV还是其他一些数据。。。
猜测和 {"autoReport":0} 有关系。。。去掉试试？

参考最新版的MTA文档
[H5接入指南 - MTA HTML5接入](http://docs.developer.qq.com/mta/fast_access/h5/access.html)
```
// 初始化
MtaH5.init({
  ...
  "autoReport":0,//是否开启自动上报(1:init完成则上报一次,0:使用pgv方法才上报)
  ...
});

```

**Comment by ChanJuanMei** [comment]
貌似还是不行呢。无论后面我能不能成功进来，都很感觉你哦，真是一个very nice的人呢，么么哒

**Comment by ChanJuanMei** [comment]
大神，可以请教你一个问题吗？我现在有个项目想要使用postcss，postcss-px2rem。配置如下
```
var lessLoader =  [
  {
      loader: 'css-loader'
  }, 
  {
      loader: 'postcss-loader',
      options: {
          plugins: (loader) => [
              require('autoprefixer')({
                  browsers: ['last 15 versions']
              }),
          require('postcss-px2rem')(px2remConfig)
          ]
      }
  },
  { loader: 'less-loader'}
]

module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                  loaders: {
                      css: ExtractTextPlugin.extract({
                        fallback: 'vue-style-loader', // <- this is a dep of vue-loader, so no need to explicitly install if using npm3
                        use: cssLoader
                      }),
                      less: ExtractTextPlugin.extract({
                        fallback: 'vue-style-loader', // <- this is a dep of vue-loader, so no need to explicitly install if using npm3
                        use: lessLoader
                      })
                  }
                }
            },
            {
                test: /\.(js)$/, use: ['babel-loader?compact=false'],
                enforce: "pre"
            },
            { 
              test: /\.css$/,
              loader: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: cssLoader
              })
            },
            {
                test: /\.less$/,
                loader: ExtractTextPlugin.extract({
                  fallback: 'style-loader',
                  use: lessLoader
                })
            }
        ]
    }
```
但是在.vue文件里面的less文件会报错。去掉这一段就是好的了
```
test: /\.vue$/,
 loader: 'vue-loader',
 options: 
中的
less: ExtractTextPlugin.extract({
                        fallback: 'vue-style-loader', // <- this is a dep of vue-loader, so no need to explicitly install if using npm3
                        use: lessLoader
                      })
```
 请问一下这里要怎么该才行，如果要有行内样式，又该怎么抽出

**Comment by ChanJuanMei** [comment]
@Thunf

**Comment by ChanJuanMei** [comment]
![image](https://user-images.githubusercontent.com/27205051/42196505-de95ef0a-7eb0-11e8-8828-ae41c838c366.png)
 大神，build这个项目的时候出现上面那个错误是因为什么啊
